### PR TITLE
Migrate from dep to go modules

### PR DESCRIPTION
**Pull request by chez-shanpu**
This PR migrates package manager from dep to go modules.
And also upgrade packages.

### CODE REVIEW

**Comment by chez-shanpu** [comment]
Currently, I'm testing these changes in my environment.
After testing them, I'll make this PR "Ready for review".

**Comment by nghialv** [comment]
@chez-shanpu Thanks for your pull request.
Could you please remove the `vendor` directory and add it into the `.gitignore` since we don't need to store it in Git?

**Comment by chez-shanpu** [comment]
@nghialv Thank you for reviewing! I removed `vendor/` and add it into the `.gitignore`.
Could you review it again?

**Comment by nghialv** [comment]
@chez-shanpu Thank you for your great work!

**Pull request merged**
